zephyr: prj.conf: fix compilation error due to 'const'
Fix this compilation error:

.../rtos-benchmark/src/zephyr/arch/riscv/core/arch_util.c:4:32:
  error:
  conflicting types for '_sw_isr_table';
  have 'struct _isr_table_entry[]'

.../zephyr/include/zephyr/sw_isr_table.h:51:25:
  note:
  previous declaration of '_sw_isr_table'
  with type 'const struct _isr_table_entry[]'

Signed-off-by: Josuah Demangeon <me@josuah.net>